package view;

import controller.Escalonador;
import java.awt.Color;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import model.Tabela;


public class telaPrincipal extends javax.swing.JFrame implements Runnable {

    private Escalonador escalonator;
    private Tabela processos;
    private ButtonGroup escalonadores;
    private Thread comecar;

    public telaPrincipal(Escalonador esc) {
        initComponents();
        escalonadores = new ButtonGroup();

        escalonadores.add(jRadioFCFS);
        escalonadores.add(jRadioJobCurto);
        escalonadores.add(jRadioLoteria);
        escalonadores.add(jRadioMenorTempoRestante);
        escalonadores.add(jRadioPrioridades);
        escalonadores.add(jRadioRoundRobin);
        this.escalonator = esc;
        this.processos = new Tabela(escalonator.getProcessosAtivos());
        this.setTitle("Escalonador de Processos");

        jTable1.setModel(processos);

        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        escalonadoress = new javax.swing.ButtonGroup();
        jRadioFCFS = new javax.swing.JRadioButton();
        jRadioJobCurto = new javax.swing.JRadioButton();
        jRadioMenorTempoRestante = new javax.swing.JRadioButton();
        jRadioRoundRobin = new javax.swing.JRadioButton();
        jRadioPrioridades = new javax.swing.JRadioButton();
        jRadioLoteria = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jClock = new javax.swing.JLabel();
        jProcessando = new javax.swing.JLabel();
        jQuantum = new javax.swing.JLabel();
        textQuantum = new javax.swing.JTextField();
        textContexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textManutencao = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioFCFS.setText("FCFS");
        jRadioFCFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFCFSActionPerformed(evt);
            }
        });

        jRadioJobCurto.setText("Job mais curto");
        jRadioJobCurto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioJobCurtoActionPerformed(evt);
            }
        });

        jRadioMenorTempoRestante.setText("Menor tempo restante");
        jRadioMenorTempoRestante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMenorTempoRestanteActionPerformed(evt);
            }
        });

        jRadioRoundRobin.setText("Round Robin");
        jRadioRoundRobin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRoundRobinActionPerformed(evt);
            }
        });

        jRadioPrioridades.setText("Prioridades");
        jRadioPrioridades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPrioridadesActionPerformed(evt);
            }
        });

        jRadioLoteria.setText("Loteria");
        jRadioLoteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLoteriaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Arquivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Executar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Step-by-Step");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("1 Segundo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jClock.setText("Clock:");

        jProcessando.setText(" ");

        jQuantum.setText("Processador");

        textQuantum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantumActionPerformed(evt);
            }
        });
        textQuantum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textQuantumKeyTyped(evt);
            }
        });

        textContexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textContextoKeyTyped(evt);
            }
        });

        jLabel2.setText("Quantum");

        jLabel3.setText("Troca de Contexto");

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Resultado");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel4.setText("Manutencao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3)
                        .addGap(40, 40, 40)
                        .addComponent(jButton4)
                        .addGap(39, 39, 39)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jClock, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jQuantum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jProcessando)
                                                .addGap(31, 31, 31))
                                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioLoteria, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jRadioPrioridades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioRoundRobin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioMenorTempoRestante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                                .addComponent(jRadioJobCurto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioFCFS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(0, 37, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textQuantum, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(textContexto, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(textManutencao))))))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jClock)
                .addGap(18, 18, 18)
                .addComponent(jQuantum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton6))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProcessando)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jRadioFCFS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioJobCurto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioMenorTempoRestante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioRoundRobin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioPrioridades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioLoteria)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(textQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(textContexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(textManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jButton5)
                        .addGap(49, 49, 49))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        escalonator.executar();
        printTable(jTable1, processos);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        escalonator.umClock();
        printTable(jTable1, processos);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        escalonator.leituraDoArquivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioFCFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFCFSActionPerformed

        escalonator.setEscalonador(0);
        escalonator.setTamanhoTrocaDeContexto(0);
        escalonator.getXeon().setQuantum(0);

    }//GEN-LAST:event_jRadioFCFSActionPerformed

    private void jRadioJobCurtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioJobCurtoActionPerformed

        escalonator.setEscalonador(1);
        escalonator.setTamanhoTrocaDeContexto(0);
        escalonator.getXeon().setQuantum(0);


    }//GEN-LAST:event_jRadioJobCurtoActionPerformed

    private void jRadioMenorTempoRestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMenorTempoRestanteActionPerformed

        escalonator.setEscalonador(2);
        escalonator.setTamanhoTrocaDeContexto(0);
        escalonator.getXeon().setQuantum(1);

    }//GEN-LAST:event_jRadioMenorTempoRestanteActionPerformed

    private void jRadioRoundRobinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRoundRobinActionPerformed
        escalonator.setEscalonador(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioRoundRobinActionPerformed

    private void jRadioPrioridadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPrioridadesActionPerformed
        escalonator.setEscalonador(4);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioPrioridadesActionPerformed

    private void jRadioLoteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLoteriaActionPerformed
        escalonator.setEscalonador(5);

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioLoteriaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        comecar = new Thread(escalonator);
        comecar.start();


    }//GEN-LAST:event_jButton4ActionPerformed

    private void textQuantumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantumActionPerformed


    }//GEN-LAST:event_textQuantumActionPerformed

    private void textQuantumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textQuantumKeyTyped


    }//GEN-LAST:event_textQuantumKeyTyped

    private void textContextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textContextoKeyTyped

    }//GEN-LAST:event_textContextoKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (!(textContexto.equals(""))) {

            int valor = Integer.parseInt(textContexto.getText());
//            if (valor > 0) {
//                valor--;
//            }

            escalonator.setTamanhoTrocaDeContexto(valor);
            System.out.println(textContexto.getText());
        }
        if (!(textContexto.equals(""))) {
            escalonator.getXeon().setQuantum(Integer.parseInt(textQuantum.getText()));
        }

        if (!(textManutencao.equals(""))) {
            escalonator.setTempoManutencao(Integer.parseInt(textManutencao.getText()));
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        escalonator.resultados();


    }//GEN-LAST:event_jButton6ActionPerformed

    public void atualizaTabela() {
        printTable(jTable1, processos);
    }

    private void printTable(JTable tabela, Tabela table) {

        tabela.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable tabela, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                //  JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, true, hasFocus, linha, column);
                JLabel label1 = (JLabel) super.getTableCellRendererComponent(tabela, value, false, hasFocus, row, column);

                Color c = Color.WHITE;

                Object texto = tabela.getValueAt(row, 1);

                label1.setBackground(c);
                // tabela.setSelectionForeground(Color.green);
                return label1;
            }

        });

        table.fireTableDataChanged();

        jClock.setText("Clock: " + (escalonator.getTempoAtual() - 1));
        jQuantum.setText("Quantum Restante:" + escalonator.getXeon().getQuantumRestante());

        if (!escalonator.getXeon().isVazio()) {
            jProcessando.setText(escalonator.getXeon().getExecutando().getTempoChegada() + "   " + escalonator.getXeon().getExecutando().getTempoServico() + "   " + escalonator.getXeon().getExecutando().getPrioridadeOriginal() + "   " + escalonator.getXeon().getExecutando().getRestante());
        } else {
            jProcessando.setText("Processador vazio");
        }

        if (escalonator.getProcessosAtivos().isEmpty() && escalonator.getListaDeProcessos().isEmpty() && escalonator.getXeon().isVazio()) {
            JOptionPane.showMessageDialog(rootPane, "Finalizou simulação");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup escalonadoress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jClock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jProcessando;
    private javax.swing.JLabel jQuantum;
    private javax.swing.JRadioButton jRadioFCFS;
    private javax.swing.JRadioButton jRadioJobCurto;
    private javax.swing.JRadioButton jRadioLoteria;
    private javax.swing.JRadioButton jRadioMenorTempoRestante;
    private javax.swing.JRadioButton jRadioPrioridades;
    private javax.swing.JRadioButton jRadioRoundRobin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textContexto;
    private javax.swing.JTextField textManutencao;
    private javax.swing.JTextField textQuantum;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
